export const COUNTRY_CODES = [
  { code: "+1", country: "US", flag: "\u{1F1FA}\u{1F1F8}", label: "United States" },
  { code: "+1", country: "CA", flag: "\u{1F1E8}\u{1F1E6}", label: "Canada" },
  { code: "+44", country: "GB", flag: "\u{1F1EC}\u{1F1E7}", label: "United Kingdom" },
  { code: "+61", country: "AU", flag: "\u{1F1E6}\u{1F1FA}", label: "Australia" },
  { code: "+64", country: "NZ", flag: "\u{1F1F3}\u{1F1FF}", label: "New Zealand" },
  { code: "+33", country: "FR", flag: "\u{1F1EB}\u{1F1F7}", label: "France" },
  { code: "+49", country: "DE", flag: "\u{1F1E9}\u{1F1EA}", label: "Germany" },
  { code: "+31", country: "NL", flag: "\u{1F1F3}\u{1F1F1}", label: "Netherlands" },
  { code: "+32", country: "BE", flag: "\u{1F1E7}\u{1F1EA}", label: "Belgium" },
  { code: "+48", country: "PL", flag: "\u{1F1F5}\u{1F1F1}", label: "Poland" },
  { code: "+39", country: "IT", flag: "\u{1F1EE}\u{1F1F9}", label: "Italy" },
  { code: "+34", country: "ES", flag: "\u{1F1EA}\u{1F1F8}", label: "Spain" },
  { code: "+351", country: "PT", flag: "\u{1F1F5}\u{1F1F9}", label: "Portugal" },
  { code: "+43", country: "AT", flag: "\u{1F1E6}\u{1F1F9}", label: "Austria" },
  { code: "+41", country: "CH", flag: "\u{1F1E8}\u{1F1ED}", label: "Switzerland" },
  { code: "+420", country: "CZ", flag: "\u{1F1E8}\u{1F1FF}", label: "Czech Republic" },
  { code: "+421", country: "SK", flag: "\u{1F1F8}\u{1F1F0}", label: "Slovakia" },
  { code: "+30", country: "GR", flag: "\u{1F1EC}\u{1F1F7}", label: "Greece" },
  { code: "+46", country: "SE", flag: "\u{1F1F8}\u{1F1EA}", label: "Sweden" },
  { code: "+358", country: "FI", flag: "\u{1F1EB}\u{1F1EE}", label: "Finland" },
  { code: "+36", country: "HU", flag: "\u{1F1ED}\u{1F1FA}", label: "Hungary" },
  { code: "+91", country: "IN", flag: "\u{1F1EE}\u{1F1F3}", label: "India" },
  { code: "+81", country: "JP", flag: "\u{1F1EF}\u{1F1F5}", label: "Japan" },
  { code: "+886", country: "TW", flag: "\u{1F1F9}\u{1F1FC}", label: "Taiwan" },
  { code: "+60", country: "MY", flag: "\u{1F1F2}\u{1F1FE}", label: "Malaysia" },
  { code: "+86", country: "CN", flag: "\u{1F1E8}\u{1F1F3}", label: "China" },
  { code: "+27", country: "ZA", flag: "\u{1F1FF}\u{1F1E6}", label: "South Africa" },
  { code: "+55", country: "BR", flag: "\u{1F1E7}\u{1F1F7}", label: "Brazil" },
  { code: "+54", country: "AR", flag: "\u{1F1E6}\u{1F1F7}", label: "Argentina" },
  { code: "+57", country: "CO", flag: "\u{1F1E8}\u{1F1F4}", label: "Colombia" },
  { code: "+52", country: "MX", flag: "\u{1F1F2}\u{1F1FD}", label: "Mexico" },
  { code: "+251", country: "ET", flag: "\u{1F1EA}\u{1F1F9}", label: "Ethiopia" },
  { code: "+971", country: "AE", flag: "\u{1F1E6}\u{1F1EA}", label: "UAE" },
  { code: "+966", country: "SA", flag: "\u{1F1F8}\u{1F1E6}", label: "Saudi Arabia" },
  { code: "+90", country: "TR", flag: "\u{1F1F9}\u{1F1F7}", label: "Turkey" },
  { code: "+234", country: "NG", flag: "\u{1F1F3}\u{1F1EC}", label: "Nigeria" },
  { code: "+254", country: "KE", flag: "\u{1F1F0}\u{1F1EA}", label: "Kenya" },
  { code: "+20", country: "EG", flag: "\u{1F1EA}\u{1F1EC}", label: "Egypt" },
];
